import {sql} from "@vercel/postgres";
import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {ADMIN_SESSION_COOKIE,isValidAdminSession} from "@/lib/adminSession";
export const dynamic="force-dynamic";
type Setup={id:number;name:string;weightKg:number};
let schemaPromise:Promise<unknown>|null=null;
function schema(){schemaPromise||=Promise.all([sql`CREATE TABLE IF NOT EXISTS trussLoadingResult(registration_id BIGINT PRIMARY KEY,team_registration_id BIGINT NOT NULL,team_name TEXT NOT NULL,truss_weight_grams NUMERIC(12,3),setup_number INTEGER CHECK(setup_number BETWEEN 1 AND 4),added_load_kg NUMERIC(12,3),weight_updated_at TIMESTAMPTZ,load_updated_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,sql`CREATE TABLE IF NOT EXISTS trussLoadingSetup(id INTEGER PRIMARY KEY CHECK(id BETWEEN 1 AND 4),name TEXT NOT NULL,weight_kg NUMERIC(12,3) NOT NULL CHECK(weight_kg>0),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`]).then(()=>sql`INSERT INTO trussLoadingSetup(id,name,weight_kg)VALUES(1,'Setup-01',6),(2,'Setup-02',6),(3,'Setup-03',6),(4,'Setup-04',6)ON CONFLICT(id)DO NOTHING`).catch(e=>{schemaPromise=null;throw e});return schemaPromise}
function auth(){return isValidAdminSession(cookies().get(ADMIN_SESSION_COOKIE)?.value)}
async function setups():Promise<Setup[]>{const q=await sql`SELECT id,name,weight_kg FROM trussLoadingSetup ORDER BY id`;return q.rows.map(r=>({id:Number(r.id),name:r.name,weightKg:Number(r.weight_kg)}))}
async function teams(ss:Setup[]){const q=await sql`SELECT t.id team_registration_id,t.registration_id,t.teamname,l.truss_weight_grams,l.setup_number,l.added_load_kg FROM teamRegistrationData t JOIN registrationData r ON r.id=t.registration_id LEFT JOIN trussLoadingResult l ON l.registration_id=t.registration_id WHERE LOWER(t.event)='truss' AND r.ispaid=TRUE AND NOT EXISTS(SELECT 1 FROM cancelledRegistrationData c WHERE c.registration_id=t.registration_id) ORDER BY t.registration_id,t.id`;return q.rows.map(r=>{const trussWeightGrams=r.truss_weight_grams==null?null:Number(r.truss_weight_grams),setupNumber=r.setup_number==null?null:Number(r.setup_number),addedLoadKg=r.added_load_kg==null?null:Number(r.added_load_kg),s=ss.find(x=>x.id===setupNumber),appliedLoadKg=s&&addedLoadKg!=null?s.weightKg+addedLoadKg:null,efficiency=appliedLoadKg!=null&&trussWeightGrams?Number((appliedLoadKg/(trussWeightGrams/1000)).toFixed(8)):null;return{registrationId:Number(r.registration_id),teamRegistrationId:Number(r.team_registration_id),teamName:r.teamname,trussWeightGrams,setupNumber,addedLoadKg,appliedLoadKg,efficiency}})}
async function payload(){const s=await setups();return{setups:s,teams:await teams(s)}}
export async function GET(){if(!auth())return NextResponse.json({message:"Unauthorized"},{status:401});try{await schema();return NextResponse.json(await payload(),{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return NextResponse.json({message:"Unable to load Truss Combat data."},{status:500})}}
export async function POST(req:Request){if(!auth())return NextResponse.json({message:"Unauthorized"},{status:401});try{await schema();const b=await req.json(),id=Number(b.registrationId),action=String(b.action||"");if(!Number.isInteger(id)||id<=0)return NextResponse.json({message:"Select a valid registration ID."},{status:400});const q=await sql`SELECT t.id,t.teamname FROM teamRegistrationData t JOIN registrationData r ON r.id=t.registration_id WHERE t.registration_id=${id} AND LOWER(t.event)='truss' AND r.ispaid=TRUE AND NOT EXISTS(SELECT 1 FROM cancelledRegistrationData c WHERE c.registration_id=t.registration_id) ORDER BY t.id LIMIT 1`,t=q.rows[0];if(!t)return NextResponse.json({message:"Active paid Truss team not found."},{status:404});if(action==="save-weight"){const g=Number(b.trussWeightGrams);if(!Number.isFinite(g)||g<=0)return NextResponse.json({message:"Enter a truss weight greater than 0 grams."},{status:400});const saved=await sql`INSERT INTO trussLoadingResult(registration_id,team_registration_id,team_name,truss_weight_grams,weight_updated_at,updated_at)VALUES(${id},${t.id},${t.teamname},${g},NOW(),NOW())ON CONFLICT(registration_id)DO UPDATE SET team_registration_id=EXCLUDED.team_registration_id,team_name=EXCLUDED.team_name,truss_weight_grams=EXCLUDED.truss_weight_grams,weight_updated_at=NOW(),updated_at=NOW() WHERE trussLoadingResult.truss_weight_grams IS NULL RETURNING registration_id`;if(!saved.rowCount)return NextResponse.json({message:"Truss weight is already saved. Only an administrator can change it."},{status:409})}else if(action==="save-load"){const s=Number(b.setupNumber),l=Number(b.addedLoadKg);if(!Number.isInteger(s)||s<1||s>4)return NextResponse.json({message:"Select a valid loading setup."},{status:400});if(!Number.isFinite(l)||l<0)return NextResponse.json({message:"Enter a valid applied load in kg."},{status:400});const saved=await sql`INSERT INTO trussLoadingResult(registration_id,team_registration_id,team_name,setup_number,added_load_kg,load_updated_at,updated_at)VALUES(${id},${t.id},${t.teamname},${s},${l},NOW(),NOW())ON CONFLICT(registration_id)DO UPDATE SET team_registration_id=EXCLUDED.team_registration_id,team_name=EXCLUDED.team_name,setup_number=EXCLUDED.setup_number,added_load_kg=EXCLUDED.added_load_kg,load_updated_at=NOW(),updated_at=NOW() WHERE trussLoadingResult.setup_number IS NULL AND trussLoadingResult.added_load_kg IS NULL RETURNING registration_id`;if(!saved.rowCount)return NextResponse.json({message:"Applied load is already saved. Only an administrator can change it."},{status:409})}else return NextResponse.json({message:"Invalid loading action."},{status:400});return NextResponse.json({success:true,...await payload()},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return NextResponse.json({message:"Unable to save this loading result."},{status:500})}}