"use client";
import {FormEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import TrussFestival from "@/components/TrussFestival";
import {trussSlots} from "@/config/competitionSchedule";
type Setup={id:number;name:string;weightKg:number};type Team={registrationId:number;teamRegistrationId:number;teamName:string;trussWeightGrams:number|null;setupNumber:number|null;addedLoadKg:number|null;appliedLoadKg:number|null;efficiency:number|null};type Data={setups:Setup[];teams:Team[]};
const fmt=(n:number|null,d=2)=>n==null?"—":n.toFixed(d);
function podiumSignature(teams:Team[]){const ranked=[...teams].filter(t=>t.efficiency!=null).sort((a,b)=>b.efficiency!-a.efficiency!||a.registrationId-b.registrationId),levels:number[]=[];for(const team of ranked){if(!levels.includes(team.efficiency!))levels.push(team.efficiency!);if(levels.length===3)break}return ranked.filter(t=>levels.includes(t.efficiency!)).map(t=>t.registrationId+":"+t.efficiency).join("|")}
const field="rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-900 outline-none focus:border-[#6f9388] disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500";
export default function LoadingControl(){
 const[data,setData]=useState<Data>({setups:[],teams:[]}),[query,setQuery]=useState(""),[teamId,setTeamId]=useState(""),[slot,setSlot]=useState(0),[slotGroups,setSlotGroups]=useState<number[][]>([]),[grams,setGrams]=useState(""),[station,setStation]=useState(1),[load,setLoad]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[error,setError]=useState(""),[party,setParty]=useState(0),[showFestival,setShowFestival]=useState(false),[loaded,setLoaded]=useState(false);const previous=useRef(""),rankingReady=useRef(false),festivalTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function startFestival(){setParty(p=>p+1);setShowFestival(true);if(festivalTimer.current)clearTimeout(festivalTimer.current);festivalTimer.current=setTimeout(()=>setShowFestival(false),8000)}
 const refresh=useCallback(async(quiet=false)=>{try{const [r,sr]=await Promise.all([fetch("/api/loading",{cache:"no-store"}),fetch("/api/truss-schedule?payment=paid",{cache:"no-store"})]),j=await r.json(),schedule=await sr.json();if(!r.ok)throw Error(j.message);if(!sr.ok)throw Error(schedule.message);setData(j);setSlotGroups((schedule.groups||[]).map((group:{registration_id:number}[])=>group.map(team=>Number(team.registration_id))));setLoaded(true);if(!quiet)setError("")}catch(e){if(!quiet)setError(e instanceof Error?e.message:"Unable to load results.")}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(true),5000);return()=>clearInterval(timer)},[refresh]);
 const filtered=useMemo(()=>data.teams.filter(t=>(slotGroups[slot]||[]).includes(t.registrationId)),[data.teams,slotGroups,slot]),matching=useMemo(()=>{const q=query.trim().toLowerCase();return q?filtered.filter(t=>String(t.registrationId).includes(q)||t.teamName.toLowerCase().includes(q)):filtered},[filtered,query]),selected=data.teams.find(t=>String(t.registrationId)===teamId);
 useEffect(()=>{if(selected){setGrams(selected.trussWeightGrams?.toString()||"");if(selected.setupNumber)setStation(selected.setupNumber);setLoad(selected.addedLoadKg?.toString()||"")}},[selected?.registrationId]);
 const ranked=useMemo(()=>data.teams.filter(t=>t.efficiency!=null).sort((a,b)=>b.efficiency!-a.efficiency!||a.registrationId-b.registrationId),[data.teams]);
 const podium=useMemo(()=>{const out:{position:number;efficiency:number;teams:Team[]}[]=[];ranked.forEach(t=>{const last=out[out.length-1];if(last&&last.efficiency===t.efficiency)last.teams.push(t);else if(out.length<3)out.push({position:out.length+1,efficiency:t.efficiency!,teams:[t]})});return out},[ranked]);
 useEffect(()=>{if(!loaded)return;const s=podiumSignature(data.teams);if(rankingReady.current&&s&&s!==previous.current)startFestival();previous.current=s;rankingReady.current=true},[data.teams,loaded]);
 async function save(e:FormEvent,type:"weight"|"load"){e.preventDefault();setBusy(type);setError("");setNotice("");try{if(!teamId)throw Error("Select a Truss team first.");const body=type==="weight"?{action:"save-weight",registrationId:+teamId,trussWeightGrams:+grams}:{action:"save-load",registrationId:+teamId,setupNumber:station,addedLoadKg:+load};const r=await fetch("/api/loading",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.message);const nextSignature=podiumSignature(j.teams||[]);if(nextSignature&&nextSignature!==previous.current){previous.current=nextSignature;rankingReady.current=true;startFestival()}setData(j);setNotice(type==="weight"?"Truss self-weight saved.":"Loading result saved and ranked.")}catch(e){setError(e instanceof Error?e.message:"Unable to save.")}finally{setBusy("")}}
 const setup=data.setups.find(s=>s.id===station),weightLocked=selected?.trussWeightGrams!=null,loadLocked=selected?.setupNumber!=null&&selected?.addedLoadKg!=null,total=setup&&load!==""?setup.weightKg+Number(load):null,preview=total!=null&&selected?.trussWeightGrams?total/(selected.trussWeightGrams/1000):null;
 return <main className="min-h-screen bg-[#f3f7f6] px-4 py-10 text-slate-800 sm:px-6">{showFestival&&<TrussFestival key={party}/>}<div className="mx-auto max-w-7xl">
 <header className="mb-8"><h1 className="mt-2 text-4xl font-black sm:text-5xl">Truss Final Result</h1></header>
 <section className="mb-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(pos=>{const g=podium.find(x=>x.position===pos);return <article key={pos} className={"rounded-3xl border p-5 text-center shadow-sm "+["border-[#a9c5bc] bg-[#edf5f2]","border-[#dcc9a5] bg-[#faf3e5]","border-[#b8c9dc] bg-[#eef3f8]"][pos-1]}><p className="text-sm font-black uppercase tracking-widest text-[#5f776f]">Position {pos}</p>{g?<><p className="mt-3 text-2xl font-black">{g.teams.map(t=>t.registrationId).join(" · ")}</p><p className="mt-1 text-sm">{g.teams.map(t=>t.teamName).join(" / ")}</p><p className="mt-4 font-mono text-lg text-[#3f6f61]">{g.efficiency.toFixed(8)} kg/kg</p>{g.teams.length>1&&<b className="mt-3 inline-block rounded-full bg-[#ece8f1] px-3 py-1 text-xs text-[#655d72]">TIED RESULT</b>}</>:<p className="mt-5 text-slate-500">Waiting for result</p>}</article>})}</section>
 <section className="mb-6 rounded-3xl border border-slate-200 bg-white shadow-sm p-5"><h2 className="text-center text-xl font-extrabold">Fixed loading arrangements</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.setups.map(s=><div key={s.id} className="rounded-2xl bg-slate-50 p-4 text-center"><b>{s.name}</b><p className="mt-1 text-2xl font-black text-[#426f64]">{s.weightKg.toFixed(2)} kg</p></div>)}</div></section>
 <div className="mb-8 grid items-stretch gap-6 lg:h-[760px] lg:grid-cols-[minmax(0,1.15fr)_minmax(420px,.85fr)]">
 <section className="flex h-full min-h-0 flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold">Truss examination slot</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{trussSlots.map((s,i)=><button type="button" key={s.start} onClick={()=>{setSlot(i);setQuery("");setTeamId("")}} className={"rounded-xl border px-4 py-3 font-bold "+(slot===i?"border-[#073f37] bg-[#073f37] text-white":"border-slate-300 bg-white text-slate-700 hover:border-[#8aaba1]")}><span className="block text-xs uppercase tracking-wide">Slot {i+1}</span>{i+2}:00–{i+3}:00 PM</button>)}</div><label className="mt-6 block text-sm font-bold" htmlFor="team-combobox">Search team from dropdown</label><input id="team-combobox" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Type registration ID or team name" className={field+" mt-2 w-full"}/><div className="mt-3 min-h-[320px] flex-1 overflow-y-auto overscroll-contain rounded-xl lg:min-h-0 border border-slate-200 bg-slate-50 p-2">{matching.map(t=><label key={t.teamRegistrationId} className={"flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-[#e5efeb] "+(teamId===String(t.registrationId)?"bg-[#dce9e5] text-[#294d44]":"text-slate-700")}><input type="radio" name="truss-team" checked={teamId===String(t.registrationId)} onChange={()=>{setTeamId(String(t.registrationId));setQuery("")}} className="h-4 w-4 accent-[#527b70]"/><span><b>{t.registrationId}</b> — {t.teamName}</span></label>)}{!matching.length&&<p className="px-3 py-5 text-center text-sm text-slate-500">No matching team in this time slot.</p>}</div><p className="mt-2 text-sm text-slate-500">{filtered.length} teams assigned to this time slot · {matching.length} shown.</p>{selected&&<p className="mt-4 rounded-xl bg-[#edf4f1] px-4 py-3 text-[#31584e]"><b>{selected.registrationId} — {selected.teamName}</b></p>}</section>
 <div className="flex h-full flex-col gap-6"><form onSubmit={e=>void save(e,"weight")} className="rounded-3xl border border-slate-200 bg-white shadow-sm p-6"><h2 className="mt-2 text-2xl font-black">Truss self-weight</h2><label className="mt-6 block font-bold">Weight in grams</label><input type="number" min=".001" step=".001" required disabled={weightLocked} onWheel={e=>e.currentTarget.blur()} value={grams} onChange={e=>setGrams(e.target.value)} placeholder="e.g. 250" className={field+" loading-number-input mt-2 w-full text-2xl font-bold"}/><button disabled={!!busy||!teamId||weightLocked} className="mt-5 w-full rounded-xl border border-[#789b91] bg-[#dce9e5] px-5 py-3 font-black text-[#294d44] hover:bg-[#cfdfda] disabled:cursor-not-allowed disabled:hover:bg-[#dce9e5]">{busy==="weight"?"Saving…":weightLocked?"Self-weight already saved":"Save self-weight"}</button>{weightLocked&&<p className="mt-3 text-center text-sm font-semibold text-[#5f776f]">This truss weight is locked. Only an administrator can change it.</p>}</form>
 <form onSubmit={e=>void save(e,"load")} className="flex flex-1 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mt-2 text-2xl font-black">Apply load</h2><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{data.setups.map(s=><button type="button" key={s.id} disabled={loadLocked} onClick={()=>setStation(s.id)} className={"rounded-xl border px-3 py-3 text-sm font-bold "+(station===s.id?"border-[#789b91] bg-[#dce9e5] text-[#294d44]":"border-slate-300 bg-white text-slate-700")}>{s.name}<small className="block">{s.weightKg.toFixed(2)} kg</small></button>)}</div><label className="mt-5 block font-bold">Added load in kg</label><input type="number" min="0" step=".001" required disabled={loadLocked} onWheel={e=>e.currentTarget.blur()} value={load} onChange={e=>setLoad(e.target.value)} placeholder="e.g. 35" className={field+" loading-number-input mt-2 w-full text-2xl font-bold"}/><div className="mt-4 grid grid-cols-2 gap-3"><p className="rounded-xl bg-slate-50 p-3">Total applied load<b className="block text-lg text-[#5f776f]">{fmt(total,3)} kg</b></p><p className="rounded-xl bg-slate-50 p-3">Efficiency preview<b className="block text-lg text-[#3f6f61]">{fmt(preview,8)}</b></p></div><button disabled={!!busy||!teamId||loadLocked} className="mt-5 w-full rounded-xl bg-[#637f77] px-5 py-3 font-black text-white hover:bg-[#536e67] disabled:opacity-40">{busy==="load"?"Saving…":loadLocked?"Applied load already saved":"Save load & calculate"}</button>{loadLocked&&<p className="mt-3 text-center text-sm font-semibold text-[#5f776f]">This loading result is locked. Only an administrator can change it.</p>}</form></div></div>
 {error&&<p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</p>}{notice&&<p className="mb-5 rounded-xl border border-[#c9ddd6] bg-[#edf5f2] p-4 font-bold text-[#3f675c]">{notice}</p>}
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-2xl font-black">Live result</h2><p className="text-sm text-slate-600">Auto-refreshes every 5 seconds · efficiency shown to 8 decimal places</p></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-center text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-600">{<tr>{["Registration ID","Team Name","Weight of Truss (gm)","Loading Arrangement","Applied Load (kg)","Efficiency (kg/kg)"].map(h=><th key={h} className={"p-4 "+(h==="Team Name"?"text-left":"")}>{h}</th>)}</tr>}</thead><tbody>{data.teams.map(t=><tr key={t.teamRegistrationId} className="border-t border-slate-200"><td className="p-4 font-black text-[#426f64]">{t.registrationId}</td><td className="p-4 text-left font-semibold">{t.teamName}</td><td className="p-4 font-mono">{fmt(t.trussWeightGrams,3)}</td><td className="p-4 font-mono">{t.setupNumber?"Setup-0"+t.setupNumber:"—"}</td><td className="p-4 font-mono">{fmt(t.appliedLoadKg,3)}</td><td className="p-4 font-mono font-bold text-[#3f6f61]">{fmt(t.efficiency,8)}</td></tr>)}</tbody></table></div></section>
 </div></main>
}