export type Ambassador = { code: string; name: string; email: string; university: string; department: string };

const rows = [
 ['CC00','Faruque Abdullah','abdullahruet13@gmail.com','',''],
 ['CC01','Tasfia Tasnim','tasfia4works@gmail.com','AIBA','IBA'],
 ['CC02','Md. Siumur Rahman Sium','sium844@gmail.com','AUST','Civil'],
 ['CC03','Sunzida Ferdaus Sushoma','sushomasunzida19@gmail.com','AUST','Civil'],
 ['CC04','Fazal Shetab Rhythm','fazalshetab.rhythm@gmail.com','BAUET','Civil (CE)'],
 ['CC05','Md Sadat Ben Kashem Khan','sadatkhanraj07@gmail.com','BAUET','Civil'],
 ['CC06','A.R Rahman Rumon','arrumon613@gmail.com','BAUST','Civil'],
 ['CC07','Tanvir Rahman Socheton','tanvirrahman325@gmail.com','BEC','Civil'],
 ['CC08','Abrar Md Eactider Rahman Nafi','rahmannafi461@gmail.com','BUET','Civil'],
 ['CC09','MD Imam Hasan','hasanbae009@gmail.com','BUET','Civil'],
 ['CC10','Syed Mohammad Sowad','sowad1035@gmail.com','BUET','Mechanical'],
 ['CC11','Mst. Sabrina Zaman','u2211025@student.cuet.ac.bd','CUET','Biomedical'],
 ['CC12','Bipro Kumar Mandal','253-47-071@diu.edu.bd','DIU','Civil'],
 ['CC13','MD Hasibul Islam','253-47-111@diu.edu.bd','DIU','Civil'],
 ['CC14','Hriday Chandra Bhoumik','bhoumik081@gmail.com','DUET','Civil'],
 ['CC15','Mazharul Islam','eng.mitarek@gmail.com','DUET','Civil'],
 ['CC16','MD. Rumon Miah','rumon.duet882@gmail.com','DUET','Civil'],
 ['CC17','Md. Saifur Rahman Sabbir','jktsabbir@gmail.com','DUET','Civil'],
 ['CC18','Mohit Ahmed','mohitahmedpro@gmail.com','EWU','Business Admin.'],
 ['CC19','Samia Zaman Sadika','rnsadika@gmail.com','EWU','CSE'],
 ['CC20','Avijith Podder Prantu','avijithpodderprantu@gmail.com','HSTU','Civil'],
 ['CC21','MD Shahjalal Ahmed Sifat','mdshahjalalahmedsifat47@gmail.com','HSTU','Civil'],
 ['CC22','Masuma Akter Megla','masumaaktermegla@gmail.com','IUBAT','Civil'],
 ['CC23','Shahariyar Islam','23306164@iubat.edu','IUBAT','Civil'],
 ['CC24','Ismat Jerin Lamia','20232858283@juniv.edu','JU','BGE'],
 ['CC25','Ananna Rahman','rahman2223038@stud.kuet.ac.bd','KUET','BECM'],
 ['CC26','Manaf Mohtadi','manafmohtadi13@gmail.com','KUET','BECM'],
 ['CC27','Shayla Tasnim Siddiqui Oishi','oishi2323034@stud.kuet.ac.bd','KUET','BECM'],
 ['CC28','Shovon Kumar Das','dasshovon961@gmail.com','KUET','BECM'],
 ['CC29','Bikash Chakraborty','cb.bikash2003@gmail.com','LU','Civil'],
 ['CC30','Samiul Sayed Sami','samiulsayed17@gmail.com','LU','Civil'],
 ['CC31','Mazharul Islam Abid','mazharulislamabid72@gmail.com','MEC','Civil'],
 ['CC32','Md. Nur Fardosh','nur.fardosh.253@northsouth.edu','NSU','Civil & Env.'],
 ['CC33','Md Jabir Hasan Rahad','mdjhrahad52@gmail.com','PUST','Civil'],
 ['CC34','Md. Tanzim Ahmed Tonim','tanzimahmed7562@gmail.com','RUET','Architecture'],
 ['CC35','Akib Imran','akib.imran.sec.ce@gmail.com','SEC','Civil'],
 ['CC36','Md Jonayed Ahamed','jkjonayed6@gmail.com','SU','Civil'],
 ['CC37','Abdullah Jubair','ajubair2530002@bseee.uiu.ac.bd','UIU','EEE'],
 ['CC38','Md Nafiur Rahman Nafi','Nafiurrahmannafi7@gmail.com','UU','Civil'],
 ['CC39','Md. Sakib','farhan200335@gmail.com','UU','Civil'],
] as const;

export const ambassadors: Ambassador[] = rows.map(([code,name,email,university,department]) => ({code,name,email,university,department}));
export const ambassadorCodes = new Set(ambassadors.map(({code}) => code));
