"use client";
import { FileText, Mail, MapPin, Phone } from "lucide-react";
import { useRef, useState } from "react";
const items=[
["UI/UX Design","Responsive visual system, page layouts and user-experience planning.",7000],
["Public Website Pages","Home, events, schedules, archive and information pages.",8500],
["Registration System","Individual and team registration with validation workflows.",9500],
["Payment Workflow","Payment verification, slips and confirmation management.",9500],
["Admin Dashboard","Protected data access, search, editing and reporting tools.",5000],
["QR Distribution System","Participant verification, kit and lunch collection workflow.",6000],
["PDF & Certificates","Schedules, participant lists, certificates and print previews.",6500],
["Live Event Results","Truss scoring, ranking, result board and celebration mode.",6500],
["Media & Sponsor Content","Sponsor, media partner, gallery and promotional integration.",4500],
["Database & API Integration","Structured storage, API connectivity and data workflows.",8500],
["Testing & Security","Quality assurance, access protection and issue resolution.",6500],
["Deployment & Support","Production deployment, configuration and handover support.",4000],
] as const;const money=(n:number)=>new Intl.NumberFormat("en-BD").format(n);
const subtotal=items.reduce((sum,item)=>sum+item[2],0),total=subtotal;
export default function BillPage(){
return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#edf6ff_0%,#e8eef5_48%,#dce6ef_100%)] px-4 py-8 text-[#334155]">
<div className="bill-controls mx-auto mb-4 flex max-w-[210mm] items-center justify-between rounded-2xl border border-[#cfdae7] bg-white/95 p-4 shadow-[0_14px_40px_rgba(15,35,64,0.12)] backdrop-blur"><div><h1 className="font-black text-[#102a43]">Website cost memo preview</h1><p className="text-xs text-slate-500">A4 &middot; Print-ready quotation</p></div><button onClick={()=>window.print()} className="rounded-xl border border-[#1d5fa7] bg-white px-5 py-2.5 font-bold text-[#174f8b] shadow-sm transition hover:bg-[#eff6ff]">Print / Save</button></div>
<article className="bill-page relative mx-auto flex min-h-[297mm] w-[210mm] max-w-full flex-col overflow-hidden bg-white px-[10mm] pt-[9mm] shadow-[0_28px_70px_rgba(15,35,64,0.20)] ring-1 ring-[#cbd8e6]" style={{fontFamily: '"Times New Roman", Times, serif'}}>
<header className="relative -mx-[10mm] -mt-[9mm] flex flex-col items-center border-b border-[#c9d8e8] bg-gradient-to-b from-[#eff7ff] via-[#f8fbff] to-white px-[10mm] pb-4 pt-[9mm] text-center"><div className="absolute inset-x-0 top-0 h-[4px] bg-gradient-to-r from-[#102a43] via-[#1976bd] to-[#0aa4b5]"/><div className="w-[64mm]"><img src="/logo/ND.png?v=2" alt="Nexora Digital logo" className="block h-auto w-full"/></div><p className="mt-[10pt] text-[10px] font-bold italic tracking-[.18em] text-[#234d76]">Building Your Digital Identity</p><div className="mt-3 flex flex-wrap items-center justify-center gap-x-7 gap-y-2 text-[12px] font-medium text-[#314d68]"><span className="flex items-center gap-1.5"><i className="flex items-center justify-center text-[#1685b8]"><MapPin size={11}/></i>Dhaka, Bangladesh</span><span className="flex items-center gap-1.5"><i className="flex items-center justify-center text-[#1685b8]"><Phone size={11}/></i>+8801752-763249</span><a href="mailto:nexorabd2015@gmail.com" className="flex items-center gap-1.5 transition hover:text-[#087f91]"><i className="flex items-center justify-center text-[#1685b8]"><Mail size={11}/></i>nexorabd2015@gmail.com</a></div></header>

<section className="mb-3 mt-4 grid grid-cols-[1.15fr_1fr] gap-6 rounded-xl border border-[#d8e4ef] bg-gradient-to-r from-[#f4f8fc] via-white to-[#edf7fa] px-4 py-3 text-[12px] shadow-[0_4px_14px_rgba(30,64,96,0.06)]"><div><p className="grid grid-cols-[27mm_4mm_1fr]"><b>Client Name</b><span>:</span><span>Department of BECM, RUET</span></p><p className="mt-2 grid grid-cols-[27mm_4mm_1fr]"><b>Project Name</b><span>:</span><span>Construct Carnival 2.0 Website</span></p></div><div className="border-l border-[#bfd0df] pl-6"><p className="grid grid-cols-[25mm_4mm_1fr]"><b>Quotation No.</b><span>:</span><span>2026/10-138/CC-WEB</span></p><p className="mt-1 grid grid-cols-[25mm_4mm_1fr]"><b>Date</b><span>:</span><span>04 Oct 2026</span></p></div></section>
<section className="mb-3 flex gap-3 rounded-xl border-l-4 border-[#1685b8] bg-gradient-to-r from-[#eaf5ff] via-[#f5faff] to-[#ebf9f8] px-4 py-3 shadow-[0_4px_14px_rgba(30,64,96,0.06)]"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-[#1769aa] to-[#0aa4b5] text-white shadow-md"><FileText size={18}/></div><div><h3 className="text-[12px] font-black text-[#102a43]">Project Summary</h3><p className="mt-1 text-justify text-[12px] leading-[1.45] text-[#425b73]">Complete design and development of the Construct Carnival 2.0 platform, including responsive public pages, registrations, payments, database integration, administration, QR distribution, certificates, live results, testing and deployment support.</p></div></section>
<table className="w-full border-collapse overflow-hidden rounded-t-xl text-[12px] shadow-[0_5px_16px_rgba(30,64,96,0.07)]"><thead className="bg-gradient-to-r from-[#102a43] via-[#14558a] to-[#087f91] text-white"><tr><th className="w-[7%] border-r border-white/20 px-2 py-2 text-center">SL</th><th className="w-[24%] border-r border-white/20 px-2 py-2 text-center">Description</th><th className="border-r border-white/20 px-2 py-2 text-center">Details</th><th className="w-[18%] px-2 py-2 text-center">Amount (BDT)</th></tr></thead><tbody>{items.map((item,i)=><tr key={item[0]} className="odd:bg-white even:bg-[#f3f7fb]"><td className="border border-[#dce5ee] px-2 py-[5px] text-center">{i+1}</td><td className="border border-[#dce5ee] px-2 py-[5px] font-bold text-[#102a43]">{item[0]}</td><td className="border border-[#dce5ee] px-2 py-[5px] text-[#4a6178]">{item[1]}</td><td className="border border-[#dce5ee] py-[5px] pl-2 pr-[10pt] text-right font-bold text-[#163e67]">{money(item[2])}</td></tr>)}</tbody></table>
<div className="mb-3 flex h-[36px] items-center justify-between rounded-b-lg bg-gradient-to-r from-[#102a43] via-[#1769aa] to-[#08a0ad] text-white"><b className="pl-4 text-left text-[12px]">GRAND TOTAL</b><strong className="w-[18%] border-l border-white/40 py-2 pl-2 pr-[10pt] text-right text-[12px]">{money(total)}</strong></div>
<p className="mx-2 mt-3 text-[12px] text-[#405971]">Thank you for choosing <b className="text-[#087f91]">Nexora Digital.</b></p>
<div className="mt-20 flex justify-end px-3 text-[12px] leading-[1.5]"><div className="w-[47mm] border-t-2 border-[#47789f] pt-1 text-center"><b className="text-[#102a43]">Managing Director</b><p>Nexora Digital</p></div></div>
<footer className="memo-footer relative mt-auto -mx-[10mm] flex h-[52px] items-center justify-between overflow-hidden bg-gradient-to-r from-[#0b2038] via-[#123f67] to-[#087f91] px-[12mm] text-[12px] text-white"><div className="relative z-10 flex items-center gap-5"><span className="flex items-center gap-1"><MapPin size={10}/>Dhaka, Bangladesh</span><span className="flex items-center gap-1"><Phone size={10}/>+8801752-763249</span><a href="mailto:nexorabd2015@gmail.com" className="flex items-center gap-1"><Mail size={10}/>nexorabd2015@gmail.com</a></div><div className="relative z-10 text-[10px] font-bold italic">Building Your Digital Identity</div></footer>
</article></main>}