import { timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { sql } from "@vercel/postgres";
import nodemailer from "nodemailer";
import { ambassadors } from "@/lib/ambassadors";
import { createAmbassadorCertificatePdf } from "@/lib/ambassadorCertificatePdf";
function auth(value:unknown){const p=Buffer.from(typeof value==="string"?value.replace(/\s+/g,""):""),e=Buffer.from((process.env.ADMIN_PASSWORD||"").replace(/\s+/g,""));return Boolean(process.env.ADMIN_PASSWORD)&&p.length===e.length&&timingSafeEqual(p,e)}
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
export async function POST(request:Request){
  try{const {password,code,forceResend}=await request.json();if(!auth(password))return NextResponse.json({message:"Unauthorized"},{status:401});const person=ambassadors.find(item=>item.code===code);if(!person)return NextResponse.json({message:"Campus ambassador not found."},{status:404});if(!process.env.GMAIL_USER||!process.env.GMAIL_APP_PASSWORD)return NextResponse.json({message:"Email service is not configured."},{status:503});
    await sql`CREATE TABLE IF NOT EXISTS ambassadorCertificateEmailLog (ambassador_code TEXT PRIMARY KEY, recipient TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'sending', sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    const claim=await sql`INSERT INTO ambassadorCertificateEmailLog (ambassador_code,recipient,status,sent_at) VALUES (${person.code},${person.email},'sending',NOW()) ON CONFLICT (ambassador_code) DO UPDATE SET recipient=EXCLUDED.recipient,status='sending',sent_at=NOW() WHERE (ambassadorCertificateEmailLog.status='sent' AND ${forceResend===true}) OR (ambassadorCertificateEmailLog.status<>'sent' AND ambassadorCertificateEmailLog.sent_at<NOW()-INTERVAL '30 seconds') RETURNING ambassador_code`;
    if(!claim.rowCount)return NextResponse.json({success:true,alreadySent:true,message:"This ambassador already received a certificate."});
    try{const pdf=await createAmbassadorCertificatePdf(person);const transporter=nodemailer.createTransport({service:"gmail",connectionTimeout:10000,greetingTimeout:10000,socketTimeout:20000,auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}});await transporter.sendMail({from:`"Construct Carnival" <${process.env.GMAIL_USER}>`,to:person.email,subject:"Certificate of Appreciation  Campus Ambassador, Construct Carnival 2.0",text:`Dear ${person.name},\n\nThank you for your leadership and dedicated service as a Campus Ambassador for Construct Carnival 2.0. Your Certificate of Appreciation is attached.\n\nBest regards,\nConstruct Carnival 2.0`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;line-height:1.7;color:#1f2937"><p><strong>Dear ${esc(person.name)},</strong></p><p>Thank you for your outstanding leadership, outreach, and dedicated service as a <strong>Campus Ambassador</strong> for Construct Carnival 2.0.</p><p>Your official Certificate of Appreciation is attached.</p><p><strong>Ambassador ID:</strong> ${person.code}</p><p style="margin-top:28px"><strong>Best regards,</strong><br>Construct Carnival 2.0<br>Department of BECM, RUET</p></div>`,attachments:[{filename:`${person.code}-campus-ambassador-certificate.pdf`,content:pdf,contentType:"application/pdf"}]});await sql`UPDATE ambassadorCertificateEmailLog SET status='sent',sent_at=NOW() WHERE ambassador_code=${person.code}`;return NextResponse.json({success:true,message:`Certificate accepted for delivery to ${person.email}.`});
    }catch(error){await sql`DELETE FROM ambassadorCertificateEmailLog WHERE ambassador_code=${person.code} AND status='sending'`;throw error}
  }catch(error:any){console.error("AMBASSADOR CERTIFICATE EMAIL:",error);return NextResponse.json({message:error?.code==="EAUTH"?"Gmail authentication failed.":"Unable to send ambassador certificate."},{status:500})}
}
